adds permissions data job to workflow
psu-libraries/researcher-metadata pull request #706
Opened 2023-02-17 20:34 UTC by Smullz622

Fixes #690

2023-02-18 03:03 UTC, EricDurante reviewed
Depending on what we decide with regard to the comments that I already posted, we may need to change some things, so I'm going to hold off on reviewing the rest of this until we have some discussion.

2023-02-20 14:19 UTC, ajkiessl commented on app/jobs/permissions_check_job.rb
> +    if permissions.best_version == file.version
That sounds like it's on the right track and similar to what we do with the permissions check during the Scholarsphere upload.

So, maybe what we can do is loop through all the permissions we get back from the API.  If there is an Accepted Version that allows archival and has "Institutional Repository " as it's location _and_ there is no Published Version, then we store Accepted Version as it's preferred version and take it's metadata.  If there is no Accepted Version and only a Published Version in the returned permissions, then we store Published Version as the preferred version and take it's metadata.

I'm not too sure what would happen if both of the former criteria are true though.  Looking through a handful of publications we store in RMD and using their DOIs with the API, I'm not seeing any that have both.  Seems almost like they remove the Accepted Version once the Published Version is allowed, but I can't be 100% sure.  Maybe if both are there we give preference to Published Version? @Smullz622 @EricDurante

2023-02-20 14:21 UTC, ajkiessl commented on app/jobs/permissions_check_job.rb
> +    if permissions.best_version == file.version
Ah, I spoke too soon.  I found one with both.  In that case the Published Version is deemed the "best" permissions.  Maybe we use the "best" one when both are there.

2023-02-20 17:47 UTC, ajkiessl commented on app/models/publication.rb
>    end
We should use the values stored in the translation ymls to set the preferred versions values.  Like how we set valid versions in the oab_permissions_client: https://github.com/psu-libraries/researcher-metadata/blob/fd12910011be99c5931ad208eaa8f7724193ef87/app/services/oab_permissions_client.rb#L7-L8 .

2023-02-22 01:30 UTC, EricDurante requested changes
I think that we might need to change a couple of things. Let me know if I've misunderstood anything in my comments.

2023-02-22 13:43 UTC, Smullz622 commented on app/services/oab_preferred_permissions_service.rb
> +      published = true if perm['version'] == I18n.t('file_versions.published_version') && perm['can_archive'] == true && perm['locations'].map(&:downcase).include?('institutional repository')
From what I can tell, it seems that some of the metadata is different, but the metadata we are looking for (license etc) is the same for the same version. My search was far from exhaustive though, so I am not 100% positive if this is always the case.

2023-02-22 17:22 UTC, EricDurante approved these changes

2023-02-23 16:37 UTC, ajkiessl requested changes
This all looks good.  I just have one small change request.

2023-02-23 16:37 UTC, ajkiessl commented on app/models/activity_insight_oa_file.rb
> +  scope :needs_permissions_check, -> { pub_without_permissions.where(version_checked: nil).where(%{version = 'acceptedVersion' OR version = 'publishedVersion'}) }
Sorry, I didn't catch this the last time.  Can we do this like this:
```suggestion
  scope :needs_permissions_check, -> { pub_without_permissions.where(version_checked: nil).where(%{version = ? OR version = ?}, I18n.t('file_versions.accepted_version'), I18n.t('file_versions.published_version'))}
```

2023-02-23 20:14 UTC, ajkiessl approved these changes

2023-02-23 20:16 UTC, ajkiessl commented
I guess we might want to wait until CI starts working again.  I think the new enterprise SSO stuff is preventing it from running? @whereismyjetpack

2023-02-23 20:46 UTC, ajkiessl commented
The tests passed locally so I'm going to merge this.  I want to get this merged so I can incorporate it into some of the stuff I'm working on.

2023-02-23 20:46 UTC, merged